import uuid
from mcp.server.fastmcp import Context, FastMCP
from app.db.database import get_connection

mcp = FastMCP("SchedulingMCP")

@mcp.resource("context://scheduling/overview")
def scheduling_context() -> str:
    return """
Scheduling MCP Context

This server manages appointment scheduling, cancellation, rescheduling, and appointment lookup.

Important operating context:
- A valid patient ID is required before creating an appointment.
- Appointment status is one of scheduled, cancelled, or rescheduled.
- Appointment dates and times are stored as user-provided text values.
- Appointment IDs are generated by the server when appointments are scheduled.
"""


@mcp.tool()
async def schedule_appointment(
    patient_id: str,
    date: str,
    time: str,
    provider: str,
    ctx: Context
) -> dict:
    """Schedule a patient appointment."""
    context_message = f"Scheduling appointment for patient: {patient_id}"
    await ctx.info(context_message)
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("SELECT patient_id FROM patients WHERE patient_id = ?", (patient_id,))
    if not cur.fetchone():
        conn.close()
        return {
            "success": False,
            "message": "Patient ID not found.",
            "runtime_context": [context_message]
        }

    appointment_id = str(uuid.uuid4())[:8]

    cur.execute("""
        INSERT INTO appointments (
            appointment_id, patient_id, date, time, provider, status
        )
        VALUES (?, ?, ?, ?, ?, ?)
    """, (
        appointment_id,
        patient_id,
        date,
        time,
        provider,
        "scheduled"
    ))

    conn.commit()
    conn.close()

    return {
        "success": True,
        "message": f"Appointment scheduled successfully. Appointment ID: {appointment_id}",
        "appointment_id": appointment_id,
        "runtime_context": [context_message]
    }


@mcp.tool()
async def cancel_appointment(appointment_id: str, ctx: Context) -> dict:
    """Cancel an existing appointment."""
    context_message = f"Cancelling appointment: {appointment_id}"
    await ctx.info(context_message)
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("SELECT * FROM appointments WHERE appointment_id = ?", (appointment_id,))
    row = cur.fetchone()

    if not row:
        conn.close()
        return {
            "success": False,
            "message": "Appointment ID not found.",
            "runtime_context": [context_message]
        }

    cur.execute("""
        UPDATE appointments
        SET status = ?
        WHERE appointment_id = ?
    """, ("cancelled", appointment_id))

    conn.commit()
    conn.close()

    return {
        "success": True,
        "message": "Appointment cancelled successfully.",
        "runtime_context": [context_message]
    }


@mcp.tool()
async def reschedule_appointment(
    appointment_id: str,
    new_date: str,
    new_time: str,
    ctx: Context
) -> dict:
    """Reschedule an existing appointment."""
    context_message = f"Rescheduling appointment: {appointment_id}"
    await ctx.info(context_message)
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("SELECT * FROM appointments WHERE appointment_id = ?", (appointment_id,))
    row = cur.fetchone()

    if not row:
        conn.close()
        return {
            "success": False,
            "message": "Appointment ID not found.",
            "runtime_context": [context_message]
        }

    cur.execute("""
        UPDATE appointments
        SET date = ?, time = ?, status = ?
        WHERE appointment_id = ?
    """, (new_date, new_time, "rescheduled", appointment_id))

    conn.commit()
    conn.close()

    return {
        "success": True,
        "message": "Appointment rescheduled successfully.",
        "runtime_context": [context_message]
    }


@mcp.tool()
async def view_appointments(patient_id: str, ctx: Context) -> dict:
    """View appointments for a patient."""
    context_message = f"Viewing appointments for patient: {patient_id}"
    await ctx.info(context_message)
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("""
        SELECT *
        FROM appointments
        WHERE patient_id = ?
        ORDER BY date, time
    """, (patient_id,))

    rows = cur.fetchall()
    conn.close()

    return {
        "success": True,
        "appointments": [dict(row) for row in rows],
        "runtime_context": [context_message]
    }

@mcp.resource("appointments://{patient_id}/context")
def appointment_context(patient_id: str) -> str:
    """Return a compact appointment context summary for an MCP client."""
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("""
        SELECT *
        FROM appointments
        WHERE patient_id = ?
        ORDER BY date, time
    """, (patient_id,))

    rows = cur.fetchall()
    conn.close()

    if not rows:
        return f"No appointment context found for patient ID {patient_id}."

    appointment_lines = [
        (
            f"- {row['appointment_id']}: {row['date']} at {row['time']} "
            f"with {row['provider']} ({row['status']})"
        )
        for row in rows
    ]

    return "Appointment Context\n\n" + "\n".join(appointment_lines)


if __name__ == "__main__":
    mcp.run()
