import uuid
from mcp.server.fastmcp import Context, FastMCP
from app.db.database import get_connection
from datetime import datetime, date

mcp = FastMCP("PatientDataMCP")

@mcp.resource("context://patient-data/overview")
def patient_data_context() -> str:
    return """
Patient Data MCP Context

This server manages patient registration, patient profile lookup, and insurance records.

Important operating context:
- Patient IDs are generated by the server during registration.
- Date of birth must use MM/DD/YYYY format.
- Patient registration is limited by the policy resources exposed by this server.
- The state field is required for registration policy validation.
"""

@mcp.resource("policy://registration/washington-only")
def washington_registration_policy() -> str:
    return """
Patient Registration Policy

Only residents of Washington State are allowed to register.

Validation rule:
- state must be WA or Washington
- registration must be rejected for all other states
"""

@mcp.resource("policy://registration/adult-only")
def adult_registration_policy() -> str:
    return """
Patient Registration Policy

Only adults aged 18 or older may self-register.

Rules:
- Age must be >= 18
- Under 18 requires a parent or legal guardian
- Registration must be denied for minors
"""

@mcp.tool()
async def register_patient(
    full_name: str,
    dob: str,
    phone: str,
    email: str,
    state: str,
    ctx: Context
) -> dict:
    """Register a new patient."""
    context_message = f"Registering patient: {full_name}"
    await ctx.info(context_message)
    print("REGISTER PATIENT CALLED")
    print(full_name)
    print(dob)
    print(phone)
    print(email)
    print(state)
    if not is_washington_resident(state):
        return {
            "success": False,
            "error": "Registration denied. Only Washington residents are allowed to register.",
            "policy": "policy://registration/washington-only",
            "runtime_context": [context_message]
        }
    
    age = calculate_age(dob)

    if age < 18:
        return {
            "success": False,
            "message":
                "Registration denied. Patient must be at least 18 years old.",
            "policy":
                "policy://registration/adult-only",
            "runtime_context": [context_message]
        }

    patient_id = str(uuid.uuid4())[:8]

    conn = get_connection()
    cur = conn.cursor()

    cur.execute("""
        INSERT INTO patients (patient_id, full_name, dob, phone, email)
        VALUES (?, ?, ?, ?, ?)
    """, (patient_id, full_name, dob, phone, email))

    conn.commit()
    conn.close()

    return {
        "success": True,
        "message": f"Patient registered successfully. Patient ID: {patient_id}",
        "patient_id": patient_id,
        "runtime_context": [context_message]
    }


@mcp.tool()
async def get_patient(patient_id: str, ctx: Context) -> dict:
    """Get patient profile by patient ID."""
    context_message = f"Looking up patient: {patient_id}"
    await ctx.info(context_message)
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("SELECT * FROM patients WHERE patient_id = ?", (patient_id,))
    row = cur.fetchone()

    conn.close()

    if not row:
        return {
            "success": False,
            "message": "Patient not found.",
            "runtime_context": [context_message]
        }

    return {
        "success": True,
        "patient": dict(row),
        "runtime_context": [context_message]
    }


@mcp.tool()
async def update_insurance(
    patient_id: str,
    provider: str,
    member_id: str,
    group_number: str,
    ctx: Context
) -> dict:
    """Add or update patient insurance information."""
    context_message = f"Updating insurance for patient: {patient_id}"
    await ctx.info(context_message)
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("SELECT patient_id FROM patients WHERE patient_id = ?", (patient_id,))
    if not cur.fetchone():
        conn.close()
        return {
            "success": False,
            "message": "Patient ID not found.",
            "runtime_context": [context_message]
        }

    cur.execute("""
        INSERT INTO insurance_records (patient_id, provider, member_id, group_number)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(patient_id)
        DO UPDATE SET
            provider = excluded.provider,
            member_id = excluded.member_id,
            group_number = excluded.group_number
    """, (patient_id, provider, member_id, group_number))

    conn.commit()
    conn.close()

    return {
        "success": True,
        "message": "Insurance updated successfully.",
        "runtime_context": [context_message]
    }


@mcp.tool()
async def get_insurance(patient_id: str, ctx: Context) -> dict:
    """Get patient insurance information."""
    context_message = f"Looking up insurance for patient: {patient_id}"
    await ctx.info(context_message)
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("SELECT * FROM insurance_records WHERE patient_id = ?", (patient_id,))
    row = cur.fetchone()

    conn.close()

    if not row:
        return {
            "success": False,
            "message": "No insurance record found.",
            "runtime_context": [context_message]
        }

    return {
        "success": True,
        "insurance": dict(row),
        "runtime_context": [context_message]
    }

@mcp.resource("patient://{patient_id}/context")
def patient_context(patient_id: str) -> str:
    """Return a compact patient context summary for an MCP client."""
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("SELECT * FROM patients WHERE patient_id = ?", (patient_id,))
    patient = cur.fetchone()

    cur.execute("SELECT * FROM insurance_records WHERE patient_id = ?", (patient_id,))
    insurance = cur.fetchone()

    conn.close()

    if not patient:
        return f"No patient context found for patient ID {patient_id}."

    insurance_summary = "No insurance record on file."
    if insurance:
        insurance_summary = (
            f"Insurance: {insurance['provider']}, "
            f"member ID {insurance['member_id']}, "
            f"group {insurance['group_number']}."
        )

    return f"""
Patient Context

Patient ID: {patient['patient_id']}
Name: {patient['full_name']}
DOB: {patient['dob']}
Phone: {patient['phone']}
Email: {patient['email']}
{insurance_summary}
"""

def is_washington_resident(state: str) -> bool:
    if not state:
        return False

    normalized = state.strip().lower()
    return normalized in {"wa", "washington"}

def calculate_age(dob: str) -> int:
    birth_date = datetime.strptime(dob, "%m/%d/%Y").date()

    today = date.today()

    return (
        today.year
        - birth_date.year
        - ((today.month, today.day) <
           (birth_date.month, birth_date.day))
    )

if __name__ == "__main__":
    mcp.run()
